version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:@db:3306/ticket

  db:
    image: mysql:8.0
    container_name: ticket_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ticket
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ticket_phpmyadmin
    environment:
      PMA_HOST: db  # Link to the MySQL container
      MYSQL_ROOT_PASSWORD: ""  # Leave empty if no root password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
